use crate::xna::framework::graphics::Texture2D;
use windows::Win32::Graphics::Direct3D::{D3D_SRV_DIMENSION, D3D_SRV_DIMENSION_TEXTURE2D};
use windows::Win32::Graphics::Direct3D11::{D3D11_BIND_SHADER_RESOURCE, D3D11_USAGE, D3D11_USAGE_DEFAULT};
use windows::Win32::Graphics::Dxgi::Common::{DXGI_FORMAT, DXGI_FORMAT_R8G8B8A8_UNORM};

impl Texture2D {

    pub const DEFAULT_SHADER_FORMAT: DXGI_FORMAT = DXGI_FORMAT_R8G8B8A8_UNORM;
    pub const DEFAULT_SHADER_VIEW_DIMENSION: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE2D;
    pub const DEFAULT_MIP_LEVELS: u32 = 1;
    pub const DEFAULT_ARRAY_SIZE: u32 = 1;
    pub const DEFAULT_SAMPLE_DESC_COUNT: u32 = 1;
    pub const DEFAULT_USAGE: D3D11_USAGE = D3D11_USAGE_DEFAULT;
    pub const DEFAULT_BIND_FLAGS: u32 = D3D11_BIND_SHADER_RESOURCE.0 as u32;

}